import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { AuthProvider } from "./context/AuthContext";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css"; 
import AxiosConfig from "./components/AxiosConfig";
import { ServerStatusProvider } from "./context/ServerStatusContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <ServerStatusProvider>
            <Theme appearance="dark" hasBackground={false} suppressHydrationWarning>
              <Header/>
              <AxiosConfig />
              {children}
            </Theme>
          </ServerStatusProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
