# Generated by Django 5.2.4 on 2026-05-05 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мода')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('file', models.FileField(upload_to='mods/', verbose_name='Файл мода')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Версия')),
                ('category', models.CharField(choices=[('core', 'Основные'), ('world', 'Мир'), ('tech', 'Техника'), ('magic', 'Магия'), ('utility', 'Утилиты'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('status', models.CharField(choices=[('pending', 'в ожидании'), ('approved', 'одобренный'), ('rejected', 'отклоненный')], default='pending', max_length=20, verbose_name='Статус')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Скачивания')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_mods', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Мод',
                'verbose_name_plural': 'Моды',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
