# Generated by Django 5.2.4 on 2026-05-04 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название скрина')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Картинка')),
                ('status', models.CharField(choices=[('pending', 'в ожидании'), ('approved', 'одобренный'), ('rejected', 'отклоненный')], default='pending', max_length=20)),
                ('coins', models.PositiveIntegerField(default=0, verbose_name='Монеты')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_gallery', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
