# Generated by Django 5.2.4 on 2026-05-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleries',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Монеты'),
        ),
        migrations.AddField(
            model_name='galleries',
            name='tags',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=255),
        ),
    ]
