# Generated by Django 5.2.4 on 2026-05-04 16:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_galleries_coins_galleries_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleries',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Теги'),
        ),
    ]
