# Generated by Django 5.2.4 on 2026-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Администрация', max_length=100, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Обновление', 'Обновление'), ('Событие', 'Событие'), ('Техническое', 'Техническое'), ('Анонс', 'Анонс'), ('Конкурс', 'Конкурс')], default='Обновление', max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткий анонс'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
    ]
