# Generated by Django 6.0.3 on 2026-05-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mc_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
